version: "3.8"
services:
  backend:
    build: ./polemos-api
    ports:
      - "5000:80"
    environment:
      ASPNETCORE_URLS: "http://+:80"

  frontend:
    build: ./polemos-spa
    ports:
      - "8080:80"
    depends_on:
      - backend
